package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

// WorklistCmd: `leetcode-cli worklist [--limit=N] [--difficulty=easy,medium] [--tags=dp,array] [--force]`
//
// Fetches problems from your LeetCode profile filtered to NOT_ACCEPTED (status TO_DO),
// writes to worklist.md (one slug per line) sorted by frontendQuestionId ascending.
// Skips overwrite if worklist.md exists and non-empty (use --force to override).
// WorklistCmd: `leetcode-cli worklist [--limit=N] [--difficulty=easy,medium] [--tags=dp,array] [--force] [--categories=algorithms,database] [--no-shuffle]`
//
// Fetches problems from your LeetCode profile (NOT_ACCEPTED = unsolved) and
// writes them to worklist.md, one slug per line. By default shuffles the order
// so the agent doesn't process problems in strict ID-ascending order (which is
// an obvious bot pattern — easy problems first, sequential walk).
// Pulls both "algorithms" and "database" categories so SQL tasks are included.
// `fetch` decides per-task whether to solve in Go or SQL.
//
// Skips overwrite if worklist.md exists and is non-empty (use --force to override).
func WorklistCmd(args []string) {
	EnsureEnv()
	fs := flag.NewFlagSet("worklist", flag.ExitOnError)
	limit := fs.Int("limit", 0, "max problems per category (0 = all)")
	diff := fs.String("difficulty", "", "comma-sep easy,medium,hard")
	tags := fs.String("tags", "", "comma-sep tag slugs")
	force := fs.Bool("force", false, "overwrite existing worklist.md")
	categories := fs.String("categories", "algorithms,database", "comma-sep category slugs")
	noShuffle := fs.Bool("no-shuffle", false, "preserve ID-ascending order (default: shuffle)")
	if err := fs.Parse(args); err != nil {
		return
	}

	if !*force {
		if existing, _ := os.ReadFile("worklist.md"); len(strings.TrimSpace(string(existing))) > 0 {
			emitOK(map[string]interface{}{
				"total":          0,
				"written":        0,
				"skipped_reason": "already_exists",
				"file":           "worklist.md",
			})
			return
		}
	}

	c, err := NewClient()
	if err != nil {
		emitErr("SESSION_EXPIRED", err.Error())
		return
	}

	difficulty := ""
	if *diff != "" {
		difficulty = strings.ToUpper(strings.Split(*diff, ",")[0])
	}
	tagList := []string{}
	if *tags != "" {
		for _, t := range strings.Split(*tags, ",") {
			t = strings.TrimSpace(t)
			if t != "" {
				tagList = append(tagList, t)
			}
		}
	}
	cats := []string{"algorithms", "database"}
	if *categories != "" {
		cats = nil
		for _, t := range strings.Split(*categories, ",") {
			t = strings.TrimSpace(t)
			if t != "" {
				cats = append(cats, t)
			}
		}
	}

	const pageSize = 100
	var collected []listItem
	totalSeen := 0
	for _, cat := range cats {
		skip := 0
		catCount := 0
		for {
			page, t, err := c.GetProblemsetPage(pageSize, skip, cat, difficulty, "", tagList)
			if err != nil {
				switch {
				case isErr(err, "SESSION_EXPIRED"):
					emitErr("SESSION_EXPIRED", err.Error())
				default:
					emitErr("FETCH_FAILED", err.Error())
				}
				return
			}
			if totalSeen == 0 {
				totalSeen = t
			}
			collected = append(collected, page...)
			catCount += len(page)
			if *limit > 0 && catCount >= *limit {
				collected = collected[:len(collected)-len(page)+ (*limit - (catCount - len(page)))]
				break
			}
			if len(page) < pageSize {
				break
			}
			skip += pageSize
		}
	}

	// Client-side filter: unsolved = status != "ac" (case-insensitive).
	var todo []listItem
	for _, it := range collected {
		if strings.EqualFold(it.Status, "ac") {
			continue
		}
		todo = append(todo, it)
	}

	// Shuffle order unless --no-shuffle. Default shuffle breaks the obvious
	// bot pattern of "solve problems 1..N sequentially by ascending ID".
	shuffled := !*noShuffle
	if shuffled {
		for i := len(todo) - 1; i > 0; i-- {
			j := randSource.Intn(i + 1)
			todo[i], todo[j] = todo[j], todo[i]
		}
	}

	var b strings.Builder
	b.WriteString("# generated by leetcode-cli worklist; one slug per line\n")
	for _, it := range todo {
		b.WriteString(it.TitleSlug)
		b.WriteByte('\n')
	}
	if err := os.WriteFile("worklist.md", []byte(b.String()), 0o644); err != nil {
		emitErr("IO", err.Error())
		return
	}

	emitOK(map[string]interface{}{
		"total":    totalSeen,
		"written":  len(todo),
		"file":     "worklist.md",
		"shuffled": shuffled,
	})
}

// listItem is a minimal row from problemsetQuestionList
type listItem struct {
	QuestionFrontendID string `json:"frontendQuestionId"`
	Title              string `json:"title"`
	TitleSlug          string `json:"titleSlug"`
	Difficulty         string `json:"difficulty"`
	Status             string `json:"status"`
	PaidOnly           bool   `json:"paidOnly"`
}

type problemsetResp struct {
	Data struct {
		ProblemsetQuestionList struct {
			Total     int        `json:"total"`
			Questions []listItem `json:"questions"`
		} `json:"problemsetQuestionList"`
	} `json:"data"`
}

// problemsetQuestionList query (US site, verified against leetcode.com schema).
const problemsetQuery = `query problemsetQuestionList($categorySlug:String,$limit:Int,$skip:Int,$filters:QuestionListFilterInput){
  problemsetQuestionList: questionList(
    categorySlug:$categorySlug
    limit:$limit
    skip:$skip
    filters:$filters
  ) {
    total: totalNum
    questions: data {
      difficulty
      frontendQuestionId: questionFrontendId
      paidOnly: isPaidOnly
      status
      title
      titleSlug
      topicTags { name slug }
    }
  }
}`

// GetProblemsetPage returns one page of the problemset. `categorySlug` is one of
// "algorithms", "database", "shell", etc. statusFilter is non-empty only if the
// UserQuestionStatus enum on this site accepts it (we currently filter client-side).
func (c *Client) GetProblemsetPage(limit, skip int, categorySlug, difficulty, statusFilter string, tags []string) ([]listItem, int, error) {
	filters := map[string]interface{}{}
	if statusFilter != "" {
		filters["status"] = statusFilter
	}
	if difficulty != "" {
		filters["difficulty"] = difficulty
	}
	if len(tags) > 0 {
		filters["tags"] = tags
	}
	if categorySlug == "" {
		categorySlug = "algorithms"
	}
	vars := map[string]interface{}{
		"categorySlug": categorySlug,
		"limit":        limit,
		"skip":         skip,
		"filters":      filters,
	}
	var r problemsetResp
	if err := c.graphql("problemsetQuestionList", problemsetQuery, vars, &r); err != nil {
		return nil, 0, err
	}
	return r.Data.ProblemsetQuestionList.Questions, r.Data.ProblemsetQuestionList.Total, nil
}

// silence unused-import linter for fmt
var _ = fmt.Sprintf